---
name: Update API
on:
  pull_request:
    paths:
      - ".github/workflows/UpdateAPI.yaml"
  schedule:
    - cron: "0 6 * * *"  # Daily at 6 a.m. UTC
  workflow_dispatch:

jobs:
  update:
    name: AWS API Definitions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - uses: julia-actions/cache@v2
      - name: Install JuliaFormatter
        shell: julia --project=@format --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(; name="JuliaFormatter", version="1"))
      - uses: julia-actions/julia-buildpkg@v1
      # Run against the latest version, since everything merged into master will be tagged.
      - name: Update API
        shell: julia --threads=auto --project {0}
        run: |
          using AWS
          AWS.AWSMetadata.parse_aws_metadata()
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
      - name: Format code
        shell: julia --project=@format --color=yes {0}
        run: |
          using JuliaFormatter
          format("."; verbose=true)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        if: ${{ github.event_name != 'pull_request' }}
        with:
          commit-message: AWS API Definitions Updated
          reviewers: mattBrzezinski
          title: AWS API Definitions Updated
          token: ${{ secrets.GITHUB_TOKEN }}
